swib: SWIB24
days:
  - DAY 1 | Monday, 2024-11-21
  - DAY 2 | Monday, 2024-11-25
  - DAY 3 | Tuesday, 2024-11-26
  - DAY 4 | Wednesday, 2024-11-27
media_types:
  slides:
    label: Slides
    url_type: full_url
  youtube:
    label: Video
    url_type: full_url

