swib: SWIB23
days:
  - DAY 1 | Monday, 2023-09-11
  - DAY 2 | Tuesday, 2023-09-12
  - DAY 3 | Wednesday, 2023-09-13
media_types:
  slides:
    label: Slides
    url_type: local_file
  youtube:
    label: Video
    url_type: full_url

