swib: SWIB22
days:
  - DAY 1 | Monday, 2022-11-28
  - DAY 2 | Tuesday, 2022-11-29
  - DAY 3 | Wednesday, 2022-11-30
  - DAY 4 | Thursday, 2022-12-01
  - DAY 5 | Friday, 2022-12-02
media_types: 
  slides:
    label: Slides
    url_type: local_file
 
